const { sample } = require('lodash')

const names = [
  "Borage (starflower)",
  "Spring Barley",
  "Silage barley",
  "White mustard",
  "Buckwheat",
  "Fiber Flax",
  "Linseed",
  "Hairy Vetch",
  "Kohlrabi",
  "Chicory",
  "Oats +Vetch",
  "Briar Rose (Dog Rose)",
  "Red fescue",
  "Dactylis glomerata",
  "Perennial ryegrass",
  "Sweet Corn",
  "Birdsfoot trefoil",
  "Black Fallow",
  "Phacelia tanacetifolia 3.5 kg/ha + Fagopyrum 8 kg/ha",
  "Mustard + Fagopyrum",
  "Grasses (pasture)",
  "Mustard and Oats",
  "Agricultural tests",
  "Winter Barley",
  "Leonurus cardiaca (motherwort)",
  "Artichoke",
  "Rapeseed and Triticale",
  "Biodiversity Corridors of Biodiversity Margins",
  "Winter Stubble",
  "Miscanthus",
  "White Melilot (for feed)",
  "Backwoods apple",
  "Compound feed for small-seeded papilionaceous plants",
  "Peony",
  "Walnut",
  "Parsnip",
  "Red cabbage",
  "Spinach",
  "Soybean",
  "Spring Triticale",
  "White Clover",
  "Fescue ryegrass",
  "Red Top",
  "Narrow-leafed lupin",
  "Winter Colza",
  "Mustard + Phacelia tanacetifolia",
  "Bilberry",
  "Tillage Radish",
  "Redcurrant",
  "European pear",
  "Backwoods currants",
  "Celery",
  "Chives ",
  "Cucumbers and gherkins",
  "Potato",
  "Fodder Beet",
  "Kale",
  "Bushes",
  "Spring Rye",
  "Trefoil",
  "Crimson clover",
  "Blackcurrant",
  "English marigold",
  "Quince",
  "Forest",
  "Basil",
  "Fruit tree nursery",
  "orchard",
  "Zazielenienie",
  "Perennial ryegrass",
  "Culture ",
  "Cherry",
  "Napa cabbage",
  "Radish",
  "Arugula (rucola)",
  "Gooseberry",
  "Romaine lettuce",
  "Carrot",
  "Aksamitník (afrikán) jemnolistý",
  "Aksamitník (afrikán) rozkladitý",
  "Aktinidie",
  "Andělika lékařská",
  "Bedrník anýz",
  "Begonie hlíznatá",
  "Begonie hlíznatá mnohokvětá vzpřímená plnokvětá",
  "Begonie hlíznatá převislá plnokvětá",
  "Begonie hlíznatá velkokvětá plnokvětá",
  "Begonie stálekvetoucí",
  "Benedikt lékařský (čubet)",
  "Bojínek hlíznatý",
  "Borovice",
  "Brambor",
  "Brambořík perský - velkokvětý",
  "Sorghum",
  "Sudan grass",
  "Japanese poplar",
  "Sorghum",
  "2 row barley",
  "Butterhead lettuce",
  "Culture",
  "Brambořík perský - velkokvětý třepenitý",
  "Brambořík perský - velkokvětý víceplátečný",
  "Brokolice",
  "Broskvomandloň (plodová)",
  "Broskvomandloň (podnož)",
  "Broskvoň (okrasná)",
  "Broskvoň (plodová)",
  "Broskvoň (podnož)",
  "Brslen",
  "Bytel metlovitý vláskovitý",
  "Čekanka pro puky",
  "Čekanka průmyslová",
  "Celer řapíkatý",
  "Černý kořen",
  "Česnek jarní",
  "Česnek ozimý",
  "Chejr vonný",
  "Chřest",
  "Chřest péřitý",
  "Chrpa americká",
  "Chrpa pižmová",
  "Chryzantéma zahradní (listopadka)",
  "Cibule jarní",
  "Cibule ozimá",
  "Cibule sečka",
  "Čičorka pestrá",
  "Čirok metlový",
  "Divizna velkokvětá",
  "Dlouhatec obecný",
  "Dřín (svída dřín)",
  "Dub cer",
  "Dub letní",
  "Endivie (štěrbák) (eskariol)",
  "Fazol obecný keříčkový",
  "Fazol obecný pnoucí",
  "Chamomile",
  "Fennel",
  "Garden lupin",
  "Fazol šarlatový",
  "Fazol šarlatový (okrasný)",
  "Fenykl obecný (sladký)",
  "Fiala šedivá (letní)",
  "Gloxínie nádherná",
  "Heřmánek římský",
  "Heřmánkovec přímořský plnokvětý",
  "Hlaváč černopurpurový plnokvětý",
  "Hlaváč hvězdicový",
  "Hledík větší",
  "Hledík větší (nízký)",
  "Hledík větší (vysoký)",
  "Hloh (podnož)",
  "Hrachor vonný",
  "Hrách setý cukrový",
  "Hrách setý dřeňový",
  "Hrách setý kulatosemenný",
  "Hrušeň písečná (asijská) (plodová)",
  "Hrušeň (podnož)",
  "Hvozdík bradatý",
  "Hvozdík karafiál plnokvětý",
  "Iberka okoličnatá",
  "Ibišek bahenní",
  "Jablečník obecný",
  "Jabloň (okrasná)",
  "Jabloň (podnož)",
  "Jakon",
  "Ječmen jarní (dvouřadý)",
  "Ječmen jarní (víceřadý)",
  "Ječmen ozimý (dvouřadý)",
  "Ječmen ozimý (víceřadý)",
  "Jehlice rolní",
  "Jeřáb černý",
  "Jeřáb obecný",
  "Jeřáb obecný x hloh sibiřský",
  "Jestřabina východní",
  "Jetel alexandrijský",
  "Jetel alpínský",
  "Jetel červenavý",
  "Alsike Clover",
  "Green pea",
  "Carum",
  "Hybrid Ryegrass",
  "Plantago",
  "Wild carrot",
  "Romaine lettuce Mini Red",
  "Ice Lettuce",
  "Jetel horský",
  "Jetel jahodnatý",
  "Jetel kavkazský",
  "Jetel ladní",
  "Jetel panonský",
  "Jetel prostřední",
  "Jetel rolní",
  "Jetel (T. nigrescens Viv.)",
  "Jetel (Trifolium pratense L. x Trifolium medium L.)",
  "Jetel zvrácený",
  "Jílek mnohokvětý italský",
  "Jílek mnohokvětý jednoletý",
  "Jiřinka proměnlivá",
  "Jírovec maďal",
  "Jitrocel kopinatý",
  "Jonátka africká (kapská fialka)",
  "Kaštanovník jedlý",
  "Katrán etiopský",
  "Kdouloň podlouhlá (plodová)",
  "Kokarda spanilá",
  "Kokrhel luštinec",
  "Kokrhel větší",
  "Kolopejka vděčná",
  "Konopice bledožlutá",
  "Konvalinka vonná",
  "Kopretina kýlnatá",
  "Kopretina osenní",
  "Kozinec cizrnovitý",
  "Kozlík lékařský",
  "Krásenka sírožlutá",
  "Krásenka zpeřená",
  "Krásnoočko dvoubarvé",
  "Krásnoočko různolisté",
  "Křen",
  "Kukuřice cukrová",
  "White poppy seeds",
  "Linum usitatissimum L.",
  "Raspberry",
  "Wood bluegrass",
  "Einkorn wheat",
  "Rumex",
  "Kukuřice pukancová",
  "Lagenárie (podnož)",
  "Laskavec krvavý",
  "Laskavec ocasatý",
  "Lékořice lysá",
  "Len (přadný)",
  "Len velkokvětý",
  "Lesknice kanárská",
  "Lesknice vodní",
  "Levandule lékařská",
  "Libeček lékařský",
  "Lichořeřišnice větší",
  "Lilie",
  "Limonka chobotnatá",
  "Limonka čínská",
  "Lípa",
  "Lipnice obecná",
  "Lipnice roční",
  "Lipnice smáčknutá",
  "Líska obecná",
  "Lnička setá jarní",
  "Lnička setá ozimá",
  "Lobelka drobná",
  "Lopuch větší",
  "Lupina proměnlivá (andská)",
  "Maceška zahradní",
  "Mahalebka (plodová)",
  "Mahalebka (podnož)",
  "Majoránka zahradní",
  "Mák",
  "Mandloň (plodová)",
  "Mandloň (podnož)",
  "Mateřídouška",
  "Mečík",
  "Meduňka lékařská",
  "Medvědice léčivá",
  "Medyněk vlnatý",
  "Italian Ryegrass",
  "Valerianella locusta",
  "Meloun cukrový",
  "Meruňka (plodová)",
  "Meruňka (podnož)",
  "Meruzalka zlatá (plodová)",
  "Metlice trsnatá",
  "Mišpule německá",
  "Mochna křovitá",
  "Moruše",
  "Mrkev (jedlá)",
  "Mrkev (krmná)",
  "Myrobalán (plodový)",
  "Myrobalán (podnož)",
  "Náprstník vlnatý",
  "Nevadlec stříbrný hřebenitý",
  "Okurka (salátová)",
  "Oman pravý",
  "Ořešák vlašský",
  "Ostálka čárkovitá",
  "Ostálka lepá (cinie)",
  "Ostrožka stračka plnokvětá",
  "Ostružiník",
  "Oves hřebílkatý",
  "Paprika - hybrid druhů Capsicum annuum a Capsicum chinense  (podnož)",
  "Paprika (okrasná)",
  "Parcha saflorová",
  "Pavlovnie",
  "Pelargonie",
  "Pelargónie břečťanolistá",
  "Pelargónie páskatá",
  "Pelargonie páskatá (muškát)",
  "Pelargónie velkokvětá",
  "Peluška jarní",
  "Peluška ozimá",
  "Pěnišník",
  "Pěnišník (azalka)",
  "Pěnišník obtížený",
  "Pěnišník tupolistý",
  "Pěnišník tupý",
  "Pěnišník zkřížený",
  "Serradella",
  "Scallion",
  "Radish and black radish",
  "Agrostis capillaris",
  "Pšenice tvrdá jarní (okrasná)",
  "Durum winter wheat",
  "Durum summer wheat",
  "Flowers",
  "Common agrimony",
  "Petržel naťová",
  "Petúnie",
  "Petúnie zkřížená",
  "Pískavice řecké seno",
  "Plaménka Drummondova",
  "plectranthus",
  "Poháňka hřebenitá",
  "Pomněnka lesní",
  "Povíjník nachový",
  "Přísavník (loubinec) trojlaločný",
  "Proskurník lékařský",
  "Proskurník topolovka plnokvětý",
  "Prvosenka mnohokvětá",
  "Prvosenka nálevkovitá",
  "Prvosenka žahavá",
  "Psárka luční",
  "Pšenice dvouzrnka",
  "Pšenice jednozrnka",
  "dinkel wheat",
  "Psineček psí",
  "Pupalka dvouletá",
  "Pýr (prodloužený)",
  "Rajče (determinantní)",
  "Rajče (indeterminantní)",
  "Řebříček chlumní",
  "Řebříček obecný",
  "Ředkvička",
  "Řepa salátová",
  "Řepice ozimá",
  "Řepík vonný",
  "Řeřicha zahradní",
  "Réva (moštová)",
  "Castorbean",
  "Asclepias",
  "Reveň dlanitá",
  "Reveň rebarbora",
  "Rulík zlomocný",
  "Růže",
  "Růže dužnoplodá",
  "Růže hybridní",
  "Růže svraskalá",
  "Rybíz černý",
  "Šafrán, krokus",
  "Šafrán, krokus - flavus",
  "Šafrán, krokus - vernus",
  "Salát hlávkový",
  "Salát listový",
  "Salát římský",
  "Šalotka",
  "Šalvěj lékařská",
  "Šalvěj pomoučená",
  "Šalvěj zářivá",
  "Sedmikráska chudobka",
  "Sedmikráska chudobka - monstrosa",
  "Sedmikráska chudobka - tubulosa",
  "Silenka visutá",
  "Slaměnka křídlatá",
  "Sléz maurský",
  "Slézovka trojklanná",
  "Sléz přeslenitý",
  "Slivoň japonská",
  "Slivoň (plodová)",
  "Slivoň (podnož)",
  "Slunečnice roční plnokvětá",
  "Smělek štíhlý",
  "Smilek růžový",
  "Smil listenatý (slaměnka)",
  "Špenát",
  "Sporýš argentinský",
  "Sporýš kanadský",
  "Sporýš tuhý",
  "Sporýš zkřížený",
  "Srha hajní (srha Aschersonova)",
  "Starček cinerarie",
  "Štírovník bažinný",
  "Common sainfoin",
  "Papaver somniferum L.",
  "Tulip",
  "Romaine lettuce Mini Green",
  "Rutabaga",
  "Štírovník jednoletý",
  "Šťovík",
  "Svazenka shloučená",
  "Smooth Brome",
  "Sveřep (horský)",
  "Sveřep samužníkovitý",
  "Sveřep sitecký",
  "Svlačec trojbarevný",
  "Tabák",
  "Tabák křídlatý",
  "Tabák Sanderův",
  "Tavolník",
  "Titonie okrouhlolistá",
  "Tolice dětelová",
  "Tomka vonná",
  "Topol černý",
  "Topol, kříženec (Topol černý x Topol Simonův)",
  "Topolovka růžová",
  "Třapatka srstnatá",
  "Třešeň (plodová)",
  "Třešeň (podnož)",
  "Třezalka tečkovaná",
  "Trojštět žlutavý",
  "Tulipán Fosterův",
  "Tulipán Greigův",
  "Tulipán Kaufmannův",
  "Tykev - hybrid druhů Cucurbita maxima a Cucurbita moschata (podnož)",
  "Tykev velkoplodá",
  "Tymián obecný",
  "Úročník bolhoj",
  "Užanka líbezná",
  "Včelník moldavský",
  "Venidie nádherná",
  "Vikev panonská",
  "Višeň (podnož)",
  "Vodnice",
  "Lonicera kamtschatica",
  "Pea",
  "Hemp",
  "field bean",
  "Red Clover",
  "Brown mustard",
  "Hybrid lucerne",
  "Clover and pea (catch crop) 20/80",
  "Ohtetu luste",
  "Spring Barely + Colza",
  "Brown mustard",
  "Maize",
  "Bean",
  "Oats",
  "Asparagus",
  "Small onion bulb (red)",
  "Summer savory",
  "Tarragon",
  "Sunflower",
  "Safflower",
  "Vojtěška srpovitá",
  "Vratič řimbaba",
  "Vrba",
  "Vrbovka malokvětá",
  "Všelicha iberkolistá",
  "Weigelie",
  "Yzop lékařský",
  "Zářivka velkokvětá",
  "Zelí čínské",
  "Zelí pekingské",
  "Zvonek prostřední",
  "Fodder Radish (Oil Radish)",
  "Chick pea",
  "Small onion bulb (yellow)",
  "Spring  Wheat",
  "Satureja",
  "Snap pea",
  "Winter Wheat",
  "Winter rye",
  "Buckwheat + Vetches",
  "Papaver rhoeas",
  "Spring Colza",
  "Winter Canola",
  "Summer poppy",
  "permanent meadows and pastures",
  "Silage maize",
  "Triticale",
  "Common Vetch",
  "Herbs",
  "mixed cultivation",
  "Lentil",
  "Semi-natural composition of Herbaceous plant",
  "Honey crops",
  "White bean",
  "Humal alfalfa",
  "Alfalfa",
  "Plante de nutreț",
  "Sweat Lupine",
  "White Melilot",
  "Galega",
  "Phacelia",
  "Kentucky bluegrass",
  "Timothy",
  "Reed canary grass",
  "Tall Fescue",
  "Broccoli",
  "Turnip",
  "Red Onion (sown)",
  "Artemisia absinthium",
  "Black Chokeberry",
  "in arable land sown grassland",
  "Meadow Fescue",
  "Grassland used individually - operated by grazing",
  "Millet",
  "Spring spelt",
  "Strawberry",
  "Seaberry",
  "Cherry",
  "Half-sugar Beet",
  "Coriander",
  "Dill",
  "Eggplant",
  "Garlic",
  "Pumpkin",
  "Shallot",
  "Marrow-stem Kale",
  "White Cabbage",
  "Cauliflower",
  "Paprika",
  "Celeriac",
  "Jerusalem artichoke",
  "Small Naked Oat/Hulless Oat",
  "Silybum",
  "Yellow lupine",
  "Sheep fescue",
  "Foxtail millet",
  "Hard fescue",
  "Creeping bentgrass",
  "Peppermint",
  "Meadow pea",
  "Sorghum x Sudan grass",
  "Callistephus chinensis",
  "Aksamitník (afrikán) vzpřímený plnokvětý",
  "Brambořík perský",
  "Celer listový",
  "Chrpa císařská",
  "Hledík větší (polovysoký)",
  "Jabloň (plodová)",
  "Jetel bledožlutý",
  "Jetel šípovitý",
  "Kadeřávek",
  "Kostřava vláskovitá",
  "Len (olejný)",
  "Lipnice bahenní",
  "Lokanka lepá plnokvětá",
  "Catch crops mix",
  "Yellow Onion (sown)",
  "Echinacea purpurea",
  "Grassland for seed production",
  "Permanent grass used individually - mixed exploitation",
  "Brussels sprout",
  "Lettuce",
  "Meloun vodní",
  "Meruzalka zlatá (podnož)",
  "Nestařec mexický",
  "Ovsík vyvýšený",
  "Pěnišník průhonický",
  "Prvosenka bezlodyžná",
  "Rajče - hybrid druhů Solanum lycopersicum a Solanum habrochaites       (podnož)",
  "Réva (podnož)",
  "Réva (stolní)",
  "Rybíz červený",
  "Šater lepý",
  "Sléz přeslenitý kadeřavý",
  "Svazenka zvonkovitá",
  "Tařicovka přímořská",
  "Tykev fíkolistá (podnož)",
  "xTykev olejná(nepoužívat)",
  "Grassland",
  "Grasses",
  "Cereals mix",
  "Canola",
  "Durum wheat",
  "Tomato",
  "Cucumber",
  "Echium",
  "Spelt",
  "Fallow land",
  "Bluebell",
  "other oil and fiber culture",
  "Mix of legumes and other",
  "Onion",
  "Ryegrass",
  "Legumes mix",
  "Other cereals",
  "Apple tree",
  "Black Radish",
  "Parsley",
  "Other grain mix+Legumes mix",
  "Culture ",
  "Beetroot",
  "Starch potatoes",
  "Ryegrass",
  "Kaunviljade segu",
  "Ryegrass",
  "Woodland Strawberry",
  "Other cabbages",
  "Camelina",
  "Lowbush blueberry",
  "Wild Cherry",
  "Segavili",
  "Grass seed mixture",
  "cock's-foot",
  "Lotus (genus)",
  "Wheat and peas",
  "Black Mustard",
  "Cranberry",
  "Glove Thistle",
  "Lupine",
  "Field without grant",
  "Common plum",
  "Quinoa",
  "Vegetable",
  "Alpine blueberry",
  "Green manure",
  "Grasses and clover",
  "Mix of fruit and berry trees",
  "Brassica campestris",
  "Nigella sativa",
  "Black mustard",
  "Does not meet grant requirements",
  "Thorough maintenance of wetlands",
  "Maintenance of land drains (removing grass)",
  "Rowan",
  "Pea with mustard",
  "Field pea ",
  "Crisps Potatoes",
  "Egyptian Clover",
  "wheatgrass",
  "RLZP",
  "Pepper",
  "Pumpkins, zucchini, patisson",
  "6 row barley",
  "Other legume",
  "Sugar Beet",
  "Physalis",
  "Grapevine",
  "Missing",
  "Mix of crops",
  "Green Fallow",
  "Corn for fodder",
  "Rhubarb",
  "Birdsfoot Trefoil",
  "Potato for fries",
  "Other potatoes",
  "Basket willow",
  "Horned melon",
  "Corn for grain",
  "Gombo",
  "Early potato",
  "Grasses mix",
  "Mixture of grasses and legumes (Establishment)",
  "Beetroot",
  "Leek",
  "Yellow Melilot",
  "Fescue",
  "Other grain mix",
  "Other vegetable legume",
  "Galega",
  "Grasses (renewed)",
  "Timothy (40%). Red clover (60%)",
  "Legumes mix (Animals)",
  "Mix of onions",
  "Persian clover",
  "Horse bean",
  "Rice",
  "Peanut",
  "Cranberry",
  "Flattened meadow-grass",
  "Maintenance of land drains (grass left on the side of the drain)",
  "Oats and peas",
  "Creeping-gloxinia",
  "Oats, peas and barley",
  "Mix (oats, common vetch, peas)",
  "Improvement of bodies of water at risk",
  "Protection of habitat of aquatic warbler",
  "Deschampsia flexuosa (wavy hair-grass)",
  "\"SZARVASI-1\" ENERGYGRASS",
  "Grassland on arable land",
  "Seed potato",
  "Sweet potato",
  "Parsley root"
]

module.exports = () => sample(names)
