const { sample } = require('lodash')

const names = [
  "Agrostis capillaris",
  "Alfalfa",
  "Alpine blueberry",
  "Alsike Clover",
  "Apple tree",
  "Artichoke",
  "Basket willow",
  "Bean",
  "Beetroot",
  "Beetroot",
  "Bilberry",
  "Birdsfoot trefoil",
  "Black Chokeberry",
  "Black Fallow",
  "Black mustard",
  "Black Mustard",
  "Black Radish",
  "Blackcurrant",
  "Bluebell",
  "Borage (starflower)",
  "Brassica campestris",
  "Briar Rose (Dog Rose)",
  "Brown mustard",
  "Brown mustard",
  "Brussels sprout",
  "Buckwheat",
  "Callistephus chinensis",
  "Camelina",
  "Canola",
  "Carrot",
  "Carum",
  "Cauliflower",
  "Celeriac",
  "Cherry",
  "Chick pea",
  "Chives ",
  "Common plum",
  "Common sainfoin",
  "Common Vetch",
  "Coriander",
  "Cranberry",
  "Creeping bentgrass",
  "Creeping-gloxinia",
  "Crimson clover",
  "Cucumber",
  "Cucumbers and gherkins",
  "Dactylis glomerata",
  "Deschampsia flexuosa (wavy hair-grass)",
  "Dill",
  "Does not meet grant requirements",
  "Durum wheat",
  "Early potato",
  "Echium",
  "Eggplant",
  "English marigold",
  "European pear",
  "Fallow land",
  "Fescue ryegrass",
  "Fescue",
  "Fiber Flax",
  "field bean",
  "Field pea ",
  "Flattened meadow-grass",
  "Fodder Beet",
  "Fodder Radish (Oil Radish)",
  "Forest",
  "Foxtail millet",
  "Galega",
  "Galega",
  "Garlic",
  "Glove Thistle",
  "Grapevine",
  "Grasses (pasture)",
  "Grasses and clover",
  "Grasses",
  "Grassland",
  "Green manure",
  "Hairy Vetch",
  "Half-sugar Beet",
  "Hard fescue",
  "Hemp",
  "Humal alfalfa",
  "Hybrid lucerne",
  "Hybrid Ryegrass",
  "Improvement of bodies of water at risk",
  "Italian Ryegrass",
  "Japanese poplar",
  "Jerusalem artichoke",
  "Kale",
  "Kaunviljade segu",
  "Kentucky bluegrass",
  "Kohlrabi",
  "Leek",
  "Legumes mix (Animals)",
  "Legumes mix",
  "Lentil",
  "Lettuce",
  "Linseed",
  "Lowbush blueberry",
  "Lupine",
  "Maize",
  "Meadow Fescue",
  "Meadow pea",
  "Millet",
  "Missing",
  "Mix (oats, common vetch, peas)",
  "Mix of crops",
  "Mix of fruit and berry trees",
  "Mix of legumes and other",
  "Mix of onions",
  "Mixture of grasses and legumes (Establishment)",
  "Narrow-leafed lupin",
  "Nigella sativa",
  "Oats and peas",
  "Oats, peas and barley",
  "Oats",
  "Ohtetu luste",
  "Onion",
  "Other cabbages",
  "Other cereals",
  "Other grain mix",
  "Other grain mix+Legumes mix",
  "Other legume",
  "other oil and fiber culture",
  "Other potatoes",
  "Other vegetable legume",
  "Papaver somniferum L.",
  "Paprika",
  "Parsley root",
  "Parsnip",
  "Pea with mustard",
  "Pea",
  "Peppermint",
  "Perennial ryegrass",
  "Persian clover",
  "Phacelia",
  "Physalis",
  "Plantago",
  "Potato",
  "Protection of habitat of aquatic warbler",
  "Pumpkin",
  "Pumpkins, zucchini, patisson",
  "Quince",
  "Quinoa",
  "Radish and black radish",
  "Raspberry",
  "Red cabbage",
  "Red Clover",
  "Red fescue",
  "Red Top",
  "Redcurrant",
  "Reed canary grass",
  "Rhubarb",
  "Rutabaga",
  "Ryegrass",
  "Ryegrass",
  "Ryegrass",
  "Scallion",
  "Seaberry",
  "Seed potato",
  "Segavili",
  "Semi-natural composition of Herbaceous plant",
  "Serradella",
  "Sheep fescue",
  "Silage barley",
  "Silybum",
  "Small Naked Oat/Hulless Oat",
  "Soybean",
  "Spelt",
  "Spinach",
  "Spring  Wheat",
  "Spring Barley",
  "Spring Colza",
  "Spring Rye",
  "Spring spelt",
  "Spring Triticale",
  "Starch potatoes",
  "Strawberry",
  "Sugar Beet",
  "Sunflower",
  "Sweat Lupine",
  "Tall Fescue",
  "Thorough maintenance of wetlands",
  "Tillage Radish",
  "Timothy",
  "Tomato",
  "Trefoil",
  "Triticale",
  "Turnip",
  "Vegetable",
  "Wheat and peas",
  "White Cabbage",
  "White Clover",
  "White Melilot (for feed)",
  "White Melilot",
  "White mustard",
  "Wild Cherry",
  "Winter Barley",
  "Winter Canola",
  "Winter Colza",
  "Winter rye",
  "Winter Wheat",
  "Wood bluegrass",
  "Woodland Strawberry",
  "Yellow lupine",
  "Yellow Melilot",
]

module.exports = () => sample(names)
